version: '3.8'

services:
  gaussian_splatting:
    image: gaussian_splatting:author
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: gaussian_splatting_container
    volumes:
      - /data2/tushar:/data
      - ../:/workspace
    ports:
      - "8888:8888"  # Adjust the port mapping as needed
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Adjust GPU visibility as needed
    command: "/bin/bash -c 'source /etc/bash.bashrc && tail -f /dev/null && /bin/bash'"  # Keep container running
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]